language: php
php:
  - 7.4

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update > /dev/null
  - mysql -e 'CREATE DATABASE yii2advanced_test;'

before_script:
  - php -m
  - printf "\n" | pecl install -f imagick-3.4.4
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -m
  - composer install
  - php init --env=Development --overwrite=All
  - php yii_test migrate --interactive=0
  - php -S localhost:8001 -t $TRAVIS_BUILD_DIR/frontend/web/ $TRAVIS_BUILD_DIR/frontend/web/index-test.php &
  - php -S localhost:8002 -t $TRAVIS_BUILD_DIR/backend/web/ $TRAVIS_BUILD_DIR/backend/web/index-test.php &

jobs:
  include:
    - name: Base module unit test
      script:
        - cd ./modules/base
        - php ../../vendor/bin/codecept run unit
    - name: Auth module unit test
      script:
        - cd ./modules/auth
        - php ../../vendor/bin/codecept run unit
    - name: Auth module api backend test
      script:
        - cd ./modules/auth
        - pwd
        - php ../../vendor/bin/codecept run api --env backend ./tests/api/backend/
    - name: Blog module unit test
      script:
        - cd ./modules/blog
        - php ../../vendor/bin/codecept run unit
    - name: Blog module api frontend test
      script:
        - cd ./modules/auth
        - pwd
        - php ../../vendor/bin/codecept run api --env frontend ./tests/api/frontend/
    - name: Blog module api backend test
      script:
        - cd ./modules/auth
        - pwd
        - php ../../vendor/bin/codecept run api --env backend tests/api/backend/
